#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           FLWheel,       tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           FRWheel,       tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           BLWheel,       tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           BRWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lift,          tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		displayNextLCDString("Main task running");
		//motor[FLWheel] = 100;
		//motor[FRWheel] = 100;
		//motor[BLWheel] = 100;
		//motor[BRWheel] = 100;
		motor[lift] = 127;
		delay(150);
		motor[lift] = 0;
		delay(300);
		motor[lift] = -100;
		delay(100);
		break;
	}
}
